/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telhotel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alin
 */
public class CheckOut extends javax.swing.JFrame {
    Connection Con;
    ResultSet RsCheckOut;
    Statement stm;
    Double totalbiaya=0.0;
    Double uangkembalian=0.0;
    Boolean edit=false;
    transaksi freeroom = new transaksi();
    private Object[][] dataTable = null;
    private String[] header = {"Customer Name","Duration","Check In Date","Check Out Date","Price Room","Surcharge","Total Cost"};
    
    /**
     * 
     * Creates new form CheckOut
     */
    
    /**
     * Creates new form CheckOut
     */
    public CheckOut() {
        initComponents();
        open_db();
        baca_data();
        aktif(false);
    }
    
    
     private void aktif(boolean x)
    {
        txtDenda.setEnabled(x);
        txtCheckOutDate.setEnabled(x);
        txtLamaInap.setEnabled(x);
        txtRoomNo.setEnabled(x);
        txtCheckInDate.setEnabled(x);
        txtBayar.setEnabled(x);
        txtKembalian.setEnabled(x);
        txtTotalBiaya1.setEnabled(x);
        txtName.setEnabled(x);
        txtKarID.setEnabled(x);
        txtBiayaKamar.setEnabled(x);
    }
     
    private void clear(){
        txtCheckInDate.setText("");
        txtBayar.setText("");
        txtDenda.setText("");
        txtCheckOutDate.setText("");
        txtLamaInap.setText("");
        txtRoomNo.setText("");
        txtBayar.setText("");
        txtTotalBiaya1.setText("");
        txtKembalian.setText("");
        txtName.setText("");
        txtKarID.setText("");
        txtBiayaKamar.setText("");
    }
    
    private void actButton(Boolean act){
        if(act == true){
            cmdTambah.setText("Add");
            cmdKeluar.setText("Exit");
        }
        else{
            cmdTambah.setText("Save");
            cmdKeluar.setText("Cancel");
        }
    }
    //method baca data dari Mysql dimasukkan ke table pada form
    private void baca_data(){
        try{
                stm = Con.createStatement();
                RsCheckOut = stm.executeQuery("select * from check_in inner join customer on check_in.idcustomer=customer.idcustomer");
                ResultSetMetaData meta = RsCheckOut.getMetaData();
                int col = meta.getColumnCount();
                int baris = 0;
                while(RsCheckOut.next()) {
                    baris = RsCheckOut.getRow();
                }
                dataTable = new Object[baris][col];
                int x = 0;
                RsCheckOut.beforeFirst();
                while(RsCheckOut.next()) {
                    dataTable[x][0] = RsCheckOut.getString("name");
                    dataTable[x][1] = RsCheckOut.getInt("lamainap");
                    dataTable[x][2] = RsCheckOut.getString("CheckInDate");
                    dataTable[x][3] = RsCheckOut.getString("CheckoutDate");
                    dataTable[x][4] = RsCheckOut.getString("biayakamar");
                    dataTable[x][5] = RsCheckOut.getDouble("denda");
                    dataTable[x][6] = RsCheckOut.getDouble("totalbiaya");
                    x++;
                }               
                tblCheckOut.setModel(new DefaultTableModel(dataTable,header));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void open_db()
    {
        try{
        KoneksiMysql kon = new KoneksiMysql ("localhost","root","","hotel");
        Con = kon.getConnection();
        }catch (Exception e) {
        System.out.println("Error : "+e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlCheckOut = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        lblRoomNo = new javax.swing.JLabel();
        txtRoomNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbRoomType = new javax.swing.JComboBox();
        pnlCheckIn = new javax.swing.JPanel();
        lblNamacus = new javax.swing.JLabel();
        lblLamaInap = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLamaInap = new javax.swing.JTextField();
        lblCheckOutDate = new javax.swing.JLabel();
        txtCheckOutDate = new javax.swing.JTextField();
        lblCheckInDate1 = new javax.swing.JLabel();
        txtCheckInDate = new javax.swing.JTextField();
        txtKarID = new javax.swing.JTextField();
        lblCheckOutDate1 = new javax.swing.JLabel();
        txtBiayaKamar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pnlCustomer1 = new javax.swing.JPanel();
        lblCustomer1 = new javax.swing.JLabel();
        lblIDCus1 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        lblLamaInap1 = new javax.swing.JLabel();
        txtTotalBiaya1 = new javax.swing.JTextField();
        btnKembalian = new javax.swing.JButton();
        btnHitungdenda = new javax.swing.JButton();
        lblBiayaTmbah = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        cmdTambah = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCheckOut = new javax.swing.JTable();
        btnKaryawan1 = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCheckOut.setBackground(new java.awt.Color(164, 92, 44));
        pnlCheckOut.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check Out", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 10))); // NOI18N

        btnCari.setText("Search");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        lblRoomNo.setText("Room Number");

        txtRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNoActionPerformed(evt);
            }
        });

        jLabel2.setText("Room Type");

        cmbRoomType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Supperior", "Duluxe", "Suite" }));
        cmbRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCheckOutLayout = new javax.swing.GroupLayout(pnlCheckOut);
        pnlCheckOut.setLayout(pnlCheckOutLayout);
        pnlCheckOutLayout.setHorizontalGroup(
            pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCheckOutLayout.createSequentialGroup()
                        .addGroup(pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblRoomNo))
                        .addGap(35, 35, 35)
                        .addGroup(pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(cmbRoomType, 0, 136, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCheckOutLayout.createSequentialGroup()
                        .addGap(0, 173, Short.MAX_VALUE)
                        .addComponent(btnCari)))
                .addContainerGap())
        );
        pnlCheckOutLayout.setVerticalGroup(
            pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckOutLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomNo)
                    .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCari)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(pnlCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        pnlCheckIn.setBackground(new java.awt.Color(164, 92, 44));
        pnlCheckIn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 10))); // NOI18N

        lblNamacus.setText("Name");

        lblLamaInap.setText("Duration");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtLamaInap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLamaInapActionPerformed(evt);
            }
        });

        lblCheckOutDate.setText("CheckOut Date");

        lblCheckInDate1.setText("CheckIn Date");

        lblCheckOutDate1.setText("Karyawan ID");

        jLabel1.setText("Biaya Kamar");

        javax.swing.GroupLayout pnlCheckInLayout = new javax.swing.GroupLayout(pnlCheckIn);
        pnlCheckIn.setLayout(pnlCheckInLayout);
        pnlCheckInLayout.setHorizontalGroup(
            pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCheckInLayout.createSequentialGroup()
                        .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLamaInap)
                            .addComponent(lblCheckInDate1)
                            .addComponent(lblCheckOutDate)
                            .addComponent(lblCheckOutDate1))
                        .addGap(29, 29, 29)
                        .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCheckOutDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtKarID, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtLamaInap, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtCheckInDate, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addGroup(pnlCheckInLayout.createSequentialGroup()
                        .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamacus)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtBiayaKamar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );
        pnlCheckInLayout.setVerticalGroup(
            pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCheckInLayout.createSequentialGroup()
                .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBiayaKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamacus)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLamaInap)
                    .addComponent(txtLamaInap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckInDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckOutDate))
                .addGap(18, 18, 18)
                .addGroup(pnlCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckOutDate1))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel1.add(pnlCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, 310));

        pnlCustomer1.setBackground(new java.awt.Color(164, 92, 44));
        pnlCustomer1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 10))); // NOI18N

        lblCustomer1.setText("Residue");

        lblIDCus1.setText("Payment");

        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });

        lblLamaInap1.setText("Total Cost");

        txtTotalBiaya1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBiaya1ActionPerformed(evt);
            }
        });

        btnKembalian.setText("Submit");
        btnKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalianActionPerformed(evt);
            }
        });

        btnHitungdenda.setText("Submit");
        btnHitungdenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungdendaActionPerformed(evt);
            }
        });

        lblBiayaTmbah.setText("Charge");

        txtDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCustomer1Layout = new javax.swing.GroupLayout(pnlCustomer1);
        pnlCustomer1.setLayout(pnlCustomer1Layout);
        pnlCustomer1Layout.setHorizontalGroup(
            pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomer1Layout.createSequentialGroup()
                .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomer1Layout.createSequentialGroup()
                        .addContainerGap(184, Short.MAX_VALUE)
                        .addComponent(btnHitungdenda))
                    .addGroup(pnlCustomer1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblBiayaTmbah)
                        .addGap(40, 40, 40)
                        .addComponent(txtDenda, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomer1Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomer1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(btnKembalian))
                            .addGroup(pnlCustomer1Layout.createSequentialGroup()
                                .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDCus1)
                                    .addComponent(lblCustomer1)
                                    .addComponent(lblLamaInap1))
                                .addGap(26, 26, 26)
                                .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBayar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTotalBiaya1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        pnlCustomer1Layout.setVerticalGroup(
            pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiayaTmbah)
                    .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHitungdenda)
                .addGap(18, 18, 18)
                .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLamaInap1)
                    .addComponent(txtTotalBiaya1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDCus1)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKembalian)
                .addGap(18, 18, 18)
                .addGroup(pnlCustomer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomer1)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(pnlCustomer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, 310));

        cmdTambah.setText("Add");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });
        jPanel1.add(cmdTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 63, -1));

        cmdKeluar.setText("Exit");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, -1));

        pnlLogin.setBackground(new java.awt.Color(164, 92, 44));
        pnlLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 10))); // NOI18N

        tblCheckOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCheckOutMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCheckOut);
        tblCheckOut.getColumnModel().getColumn(0).setResizable(false);
        tblCheckOut.getColumnModel().getColumn(1).setResizable(false);
        tblCheckOut.getColumnModel().getColumn(2).setResizable(false);
        tblCheckOut.getColumnModel().getColumn(3).setResizable(false);
        tblCheckOut.getColumnModel().getColumn(4).setResizable(false);

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 770, 130));

        btnKaryawan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/EMPLOYEE.png"))); // NOI18N
        btnKaryawan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawan1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKaryawan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 50, -1));

        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/CHECK IN.png"))); // NOI18N
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 50, -1));

        btnCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/CHECK OUT.png"))); // NOI18N
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 50, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/LOG OUT.png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 50, -1));

        jLabel3.setText("Kingdom Hotel");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 570, 160, 20));

        jLabel5.setText("Jl. Dewata Raya 1994 ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 360, 20));

        jLabel6.setText("Bogor - Indonesia 300194");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 610, 220, 20));

        jLabel7.setText("Phone  (0251) 2324254   Email : KingdomHotel@heaven.com");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 630, 390, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/ICONBARU.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/KINGHOT.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
                try{
                    stm = Con.createStatement();
                    RsCheckOut = stm.executeQuery("SELECT * FROM check_in as ci inner join customer as cus on ci.idcustomer=cus.idcustomer WHERE RoomNumber='"+txtRoomNo.getText()+"' "
                            + "and roomtype= '"+cmbRoomType.getSelectedItem()+"' and totalbiaya = 0.0");
               int baris=0;
               while(RsCheckOut.next()) {
                        baris = RsCheckOut.getRow();
                        txtName.setText(RsCheckOut.getString("name"));
                        txtLamaInap.setText(RsCheckOut.getString("lamainap"));
                        txtCheckInDate.setText(RsCheckOut.getString("checkindate"));
                        txtBiayaKamar.setText(RsCheckOut.getString("biayakamar"));
                }
                    if(baris==1)//mengecek ada berapa files dengan pass dan user itu, kalo satu benar kalo 0 salah
                {
                    txtName.setEditable(false);
                    txtLamaInap.setEditable(false);
                    txtCheckInDate.setEditable(false);
                    txtBiayaKamar.setEditable(false);
                }
                    else
                {
                    JOptionPane.showMessageDialog(null, "Room Number "+txtRoomNo.getText()+", type "+cmbRoomType.getSelectedItem()+" there is not");
                }
                   
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }

    }//GEN-LAST:event_btnCariActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNoActionPerformed

    private void txtLamaInapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaInapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaInapActionPerformed

    private void txtDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDendaActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtKembalianActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void txtTotalBiaya1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBiaya1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTotalBiaya1ActionPerformed

    private void btnKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalianActionPerformed
        // TODO add your handling code here:
        Double bayar=Double.parseDouble(txtBayar.getText());
        uangkembalian = bayar-totalbiaya;
        String uk = Double.toString(uangkembalian);
        txtKembalian.setText(uk);
    }//GEN-LAST:event_btnKembalianActionPerformed

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        // TODO add your handling code here
        if(cmdKeluar.getText().equals("Exit")){
            int ok=JOptionPane.showConfirmDialog(rootPane,"Are you sure to exit?","Pemberitahuan",JOptionPane.YES_NO_OPTION );
            if(ok==0){
                dispose();
            }
        }
        else{
            aktif(false);
            clear();
            actButton(true);
            tblCheckOut.setEnabled(true);
        }
        //System.exit(0);
    }//GEN-LAST:event_cmdKeluarActionPerformed

    private void tblCheckOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCheckOutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCheckOutMouseClicked

    private void cmbRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoomTypeActionPerformed

    private void btnHitungdendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungdendaActionPerformed
        // TODO add your handling code here:
        Double denda = Double.parseDouble(txtDenda.getText());
        Double biayakamar = Double.parseDouble(txtBiayaKamar.getText());
        totalbiaya = biayakamar+(denda*100000);
        String total = Double.toString(totalbiaya);
        txtTotalBiaya1.setText(total);
    }//GEN-LAST:event_btnHitungdendaActionPerformed

private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        // TODO add your handling code here:    
        if(cmdTambah.getText().equals("Add")){
            aktif(true);
            tblCheckOut.setEnabled(false);
            clear();
            actButton(false);
            edit=false;
        }
        else if(cmdTambah.getText().equals("Save")){
            
            String checkOutDate=txtCheckOutDate.getText();
            Double totalbiaya=Double.parseDouble(txtTotalBiaya1.getText());
            Double denda=Double.parseDouble(txtDenda.getText());
            
            try{
                    stm.executeUpdate("update check_in set checkoutdate='"+checkOutDate+"',denda="+denda+",totalbiaya="+totalbiaya+" WHERE RoomNumber='"+txtRoomNo.getText()+"' and roomtype= '"+cmbRoomType.getSelectedItem()+"'");
                
                tblCheckOut.setModel(new DefaultTableModel(dataTable,header));
                baca_data();
                tblCheckOut.setEnabled(true);
                aktif(true);
                actButton(false);
                int roomno = Integer.parseInt(txtRoomNo.getText());
                freeroom.RoomType((String)cmbRoomType.getSelectedItem(), roomno);
            
            }catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
}//GEN-LAST:event_cmdTambahActionPerformed

    private void btnKaryawan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawan1ActionPerformed
        // TODO add your handling code here:
        new Karyawan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKaryawan1ActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        new transaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        new CheckOut().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        CheckOut a = new CheckOut();
//        a.show();
//        a.setExtendedState(MAXIMIZED_BOTH);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnHitungdenda;
    private javax.swing.JButton btnKaryawan1;
    private javax.swing.JButton btnKembalian;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JComboBox cmbRoomType;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiayaTmbah;
    private javax.swing.JLabel lblCheckInDate1;
    private javax.swing.JLabel lblCheckOutDate;
    private javax.swing.JLabel lblCheckOutDate1;
    private javax.swing.JLabel lblCustomer1;
    private javax.swing.JLabel lblIDCus1;
    private javax.swing.JLabel lblLamaInap;
    private javax.swing.JLabel lblLamaInap1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNamacus;
    private javax.swing.JLabel lblRoomNo;
    private javax.swing.JPanel pnlCheckIn;
    private javax.swing.JPanel pnlCheckOut;
    private javax.swing.JPanel pnlCustomer1;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTable tblCheckOut;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtBiayaKamar;
    private javax.swing.JTextField txtCheckInDate;
    private javax.swing.JTextField txtCheckOutDate;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtKarID;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtLamaInap;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtTotalBiaya1;
    // End of variables declaration//GEN-END:variables
}
