/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telhotel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alin
 */
public class Karyawan extends javax.swing.JFrame {

    Connection Con;
    ResultSet RsCheckIn;
    ResultSet RsUser;
    Statement stm;
    String karyawan;
    Boolean edit=false;
    private Object[][] dataTable = null;
    private String[] header = {"ID Karyawan","Name","Address","Phone Number","Jabatan","User ID"};
    String userid;
    
    /**
     * 
     * Creates new form CheckIn
     */
    /*public void setUserID(String user){
        this.userid=user;
    } 
    String getUserID(){
        return userid;
    }*/
    private void setField(){
        int row=tblKar.getSelectedRow();
        cmdHapus.setEnabled(true);
        cmdEdit.setEnabled(true);
        txtKarID.setText((String)tblKar.getValueAt(row,0));
        txtNamaKar.setText((String)tblKar.getValueAt(row,1));
        txtAddress.setText((String)tblKar.getValueAt(row,2));
        txtPhoneKar.setText((String)tblKar.getValueAt(row,3));
        cmbJabatan.setSelectedItem((String)tblKar.getValueAt(row,4));
        txtUserID.setText((String)tblKar.getValueAt(row,5));
   }
    
   public Karyawan() {
       
        initComponents();
        open_db();
        baca_data();
        aktif(false);
        pnlLogin.setVisible(false);
        cmdHapus.setEnabled(false);
        cmdEdit.setEnabled(false);
    }

     private void open_db()
    {
        try{
        KoneksiMysql kon = new KoneksiMysql ("localhost","root","","hotel");
        Con = kon.getConnection();
        }catch (Exception e) {
        System.out.println("Error : "+e);
        }
    }
    
     private void aktif(boolean x)
    {
        txtAddress.setEnabled(x);
        txtKarID.setEnabled(x);
        txtNamaKar.setEnabled(x);
        txtAddress.setEnabled(x);
        txtPass.setEnabled(x);
        txtPhoneKar.setEnabled(x);
        txtUserID.setEnabled(x);
        cmbJabatan.setEnabled(x);
        pnlLogin.setEnabled(x);
     }
     
    private void clear(){
        txtAddress.setText("");
        txtKarID.setText("");
        txtNamaKar.setText("");
        txtPass.setText("");
        txtPhoneKar.setText("");
        txtUserID.setText("");
        cmbJabatan.setSelectedItem("");
    }
    
    private void actButton(Boolean act){
        if(act == true){
            cmdTambah.setText("Add");
            cmdKeluar.setText("Exit");
        }
        else{
            cmdTambah.setText("Save");
            cmdKeluar.setText("Cancel");
        }
    }
    //method baca data dari Mysql dimasukkan ke table pada form
    private void baca_data(){
        try{
                stm = Con.createStatement();
                RsCheckIn = stm.executeQuery("select * from karyawan");
                ResultSetMetaData meta = RsCheckIn.getMetaData();
                int col = meta.getColumnCount();
                int baris = 0;
                while(RsCheckIn.next()) {
                    baris = RsCheckIn.getRow();
                }
                dataTable = new Object[baris][col];
                int x = 0;
                RsCheckIn.beforeFirst();
                while(RsCheckIn.next()) {
                    dataTable[x][0] = RsCheckIn.getString("idkaryawan");
                    dataTable[x][1] = RsCheckIn.getString("name");
                    dataTable[x][2] = RsCheckIn.getString("address");
                    dataTable[x][3] = RsCheckIn.getString("phonenumber");
                    dataTable[x][4] = RsCheckIn.getString("jabatan");
                    dataTable[x][5] = RsCheckIn.getString("userid");
                    x++;
                }
                tblKar.setModel(new DefaultTableModel(dataTable,header));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * Creates new form Karyawan
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlKaryawan = new javax.swing.JPanel();
        lblKarID = new javax.swing.JLabel();
        txtKarID = new javax.swing.JTextField();
        lblNamaKar = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhoneKar = new javax.swing.JLabel();
        txtPhoneKar = new javax.swing.JTextField();
        lblJabatan = new javax.swing.JLabel();
        cmbJabatan = new javax.swing.JComboBox();
        txtNamaKar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblKarID1 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        lblNamaKar1 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        cmdTambah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdEdit = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        pnlDaftarKar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKar = new javax.swing.JTable();
        pnlLogin = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblLogo1 = new javax.swing.JLabel();
        btnKaryawan = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        pnlKaryawan.setBackground(new java.awt.Color(164, 92, 44));
        pnlKaryawan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kayawan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 10))); // NOI18N

        lblKarID.setText("ID Karyawan");

        txtKarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKarIDActionPerformed(evt);
            }
        });

        lblNamaKar.setText("Name");

        lblAddress.setText("Address");

        lblPhoneKar.setText("Phone Number");

        txtPhoneKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneKarActionPerformed(evt);
            }
        });

        lblJabatan.setText("Jabatan");

        cmbJabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Direktur", "Admin", "Recepsionist" }));
        cmbJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJabatanActionPerformed(evt);
            }
        });

        txtNamaKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKarActionPerformed(evt);
            }
        });

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        lblKarID1.setText("UserID");

        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });

        lblNamaKar1.setText("Password");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKaryawanLayout = new javax.swing.GroupLayout(pnlKaryawan);
        pnlKaryawan.setLayout(pnlKaryawanLayout);
        pnlKaryawanLayout.setHorizontalGroup(
            pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKaryawanLayout.createSequentialGroup()
                        .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaKar)
                            .addComponent(lblKarID1)
                            .addComponent(lblNamaKar1))
                        .addGap(60, 60, 60)
                        .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(txtNamaKar)
                                    .addComponent(txtKarID))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                    .addGroup(pnlKaryawanLayout.createSequentialGroup()
                        .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneKar)
                            .addComponent(lblJabatan))
                        .addGap(36, 36, 36)
                        .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbJabatan, 0, 199, Short.MAX_VALUE)
                            .addComponent(txtPhoneKar, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
            .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlKaryawanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAddress)
                        .addComponent(lblKarID))
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        pnlKaryawanLayout.setVerticalGroup(
            pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtKarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaKar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaKar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKarID1))
                .addGap(18, 18, 18)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaKar1))
                .addGap(18, 18, 18)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneKar)
                    .addComponent(txtPhoneKar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJabatan)
                    .addComponent(cmbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(pnlKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlKaryawanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblKarID)
                    .addGap(56, 56, 56)
                    .addComponent(lblAddress)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );

        cmdTambah.setText("Add");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdHapus.setText("Delete");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdEdit.setText("Edit");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });

        cmdKeluar.setText("Exit");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        pnlDaftarKar.setBackground(new java.awt.Color(164, 92, 44));
        pnlDaftarKar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 10))); // NOI18N

        tblKar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKar);
        tblKar.getColumnModel().getColumn(0).setResizable(false);
        tblKar.getColumnModel().getColumn(1).setResizable(false);
        tblKar.getColumnModel().getColumn(2).setResizable(false);
        tblKar.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout pnlDaftarKarLayout = new javax.swing.GroupLayout(pnlDaftarKar);
        pnlDaftarKar.setLayout(pnlDaftarKarLayout);
        pnlDaftarKarLayout.setHorizontalGroup(
            pnlDaftarKarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlDaftarKarLayout.setVerticalGroup(
            pnlDaftarKarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlLogin.setBackground(new java.awt.Color(164, 92, 44));
        pnlLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 10))); // NOI18N

        lblUser.setText("Username :");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        lblPass.setText("Password  :");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/KINGHOT.png"))); // NOI18N

        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/EMPLOYEE.png"))); // NOI18N
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });

        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/CHECK IN.png"))); // NOI18N
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/CHECK OUT.png"))); // NOI18N
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icon/LOG OUT.png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/ICONBARU.png"))); // NOI18N

        jLabel2.setText("Phone  (0251) 2324254   Email : KingdomHotel@heaven.com");

        jLabel5.setText("Jl. Dewata Raya 1994 ");

        jLabel6.setText("Bogor - Indonesia 300194");

        jLabel7.setText("Kingdom Hotel");

        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addGap(956, 956, 956))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(811, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogo1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addComponent(pnlKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDaftarKar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlDaftarKar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdTambah)
                        .addGap(18, 18, 18)
                        .addComponent(cmdHapus)
                        .addGap(18, 18, 18)
                        .addComponent(cmdEdit)
                        .addGap(18, 18, 18)
                        .addComponent(cmdKeluar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        // TODO add your handling code here:
        if(cmdTambah.getText().equals("Add")){
            aktif(true);
            tblKar.setEnabled(false);
            clear();
            actButton(false);
            edit=false;
        }
        else if(cmdTambah.getText().equals("Save")){
            String karID=txtKarID.getText();
            String name=txtNamaKar.getText();
            String address=txtAddress.getText();
            String phone=txtPhoneKar.getText();
            String userID=txtUserID.getText();
            String pass=txtPass.getText();
            
        try{
                if (edit==true)
                {
                    stm.executeUpdate("update karyawan set name='"+name+"',address='"+address+"',phonenumber='"+phone+"',jabatan='"+cmbJabatan.getSelectedItem()+"',userid='"+userID+"',passid='"+pass+"' where idkaryawan='"+karID+"'");
                    
                }else
                {
                    stm.executeUpdate("INSERT into karyawan VALUES('"+name+"','"+karID+"','"+address+"','"+phone+"','"+cmbJabatan.getSelectedItem()+"','"+userID+"','"+pass+"')");
                }
                tblKar.setModel(new DefaultTableModel(dataTable,header));
                baca_data();
                actButton(true);
                aktif(false);
                pnlLogin.setVisible(false);
                tblKar.setEnabled(true);
                cmdEdit.setEnabled(false);
                cmdHapus.setEnabled(false);
            }catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        // TODO add your handling code here:
        pnlLogin.setVisible(true);
        txtUser.setText(txtUserID.getText());
        edit=true;
        aktif(false);
        actButton(false);
        txtKarID.setEnabled(false);
        txtUser.setEnabled(false);
    }//GEN-LAST:event_cmdEditActionPerformed

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        // TODO add your handling code here
        pnlLogin.setVisible(false);
        if(cmdKeluar.getText().equals("Exit")){
            int ok=JOptionPane.showConfirmDialog(rootPane,"Are you sure to exit?","Pemberitahuan",JOptionPane.YES_NO_OPTION );
            if(ok==0){
                dispose();
            }
        }
        else{
            aktif(false);
            clear();
            actButton(true);
            tblKar.setEnabled(true);

        }
        //System.exit(0);
    }//GEN-LAST:event_cmdKeluarActionPerformed

    private void txtKarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKarIDActionPerformed

    private void txtPhoneKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneKarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneKarActionPerformed

    private void cmbJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJabatanActionPerformed

    private void txtNamaKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKarActionPerformed

    private void tblKarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKarMouseClicked
        // TODO add your handling code here:
        setField();
        cmdEdit.setEnabled(true);
        cmdHapus.setEnabled(true);

    }//GEN-LAST:event_tblKarMouseClicked

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        // TODO add your handling code here:
        try{
            int ok=JOptionPane.showConfirmDialog(rootPane,"Are you sure to delete?","Pemberitahuan",JOptionPane.YES_NO_OPTION );
            if(ok==0){
            String sql="delete from karyawan where idkaryawan='" + txtKarID.getText() + "'";
            stm.executeUpdate(sql);
            baca_data();
        }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try{
            String password = new String(txtPassword.getPassword());
            stm = Con.createStatement();
            RsUser=stm.executeQuery("select * from karyawan where userID='"+
                txtUser.getText()+"' and passID= '"+password+"'");
            int baris=0;
            while(RsUser.next()) {
                baris = RsUser.getRow();
                txtPass.setText(RsUser.getString("passID"));
            }
            if(baris==1)//mengecek ada berapa files dengan pass dan user itu, kalo satu benar kalo 0 salah
            {
                JOptionPane.showMessageDialog(null, "Please edit your data!");
                aktif(true);
                tblKar.setEnabled(false);
                pnlLogin.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid, please try again! "+txtUser.getText());
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUserActionPerformed

private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        // TODO add your handling code here:
        new Karyawan().setVisible(true);
        dispose();
}//GEN-LAST:event_btnKaryawanActionPerformed

private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        new transaksi().setVisible(true);
        dispose();
}//GEN-LAST:event_btnCheckInActionPerformed

private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        new CheckOut().setVisible(true);
        dispose();
}//GEN-LAST:event_btnCheckOutActionPerformed

private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
}//GEN-LAST:event_btnLogOutActionPerformed

private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
// TODO add your handling code here:
     new laporan().setVisible(true);
        dispose();
}//GEN-LAST:event_btnReportActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReport;
    private javax.swing.JComboBox cmbJabatan;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblJabatan;
    private javax.swing.JLabel lblKarID;
    private javax.swing.JLabel lblKarID1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblNamaKar;
    private javax.swing.JLabel lblNamaKar1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhoneKar;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlDaftarKar;
    private javax.swing.JPanel pnlKaryawan;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTable tblKar;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtKarID;
    private javax.swing.JTextField txtNamaKar;
    private javax.swing.JTextField txtPass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneKar;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
