/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telhotel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Alin
 */
public class login extends javax.swing.JFrame {
    Connection Con;
    ResultSet RsUser;
    Statement stm;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        open_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAwal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblGambar2 = new javax.swing.JLabel();
        lblGambar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAwal.setBackground(new java.awt.Color(255, 153, 102));
        pnlAwal.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlAwal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlAwalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        pnlAwal.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/WELCOME.png"))); // NOI18N
        pnlAwal.add(lblLogo);
        lblLogo.setBounds(0, 0, 730, 130);

        pnlLogin.setBackground(new java.awt.Color(164, 92, 44));
        pnlLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Script", 0, 10))); // NOI18N

        lblUser.setText("Username :");

        lblPass.setText("Password  :");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pnlAwal.add(pnlLogin);
        pnlLogin.setBounds(310, 170, 280, 180);

        lblGambar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/KH.JPG"))); // NOI18N
        pnlAwal.add(lblGambar2);
        lblGambar2.setBounds(760, 290, 210, 160);

        lblGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/KHHKecil.png"))); // NOI18N
        pnlAwal.add(lblGambar);
        lblGambar.setBounds(760, 140, 200, 150);

        jLabel1.setText("Please Login to enter this system");
        pnlAwal.add(jLabel1);
        jLabel1.setBounds(310, 130, 230, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/ICONBARU.png"))); // NOI18N
        pnlAwal.add(jLabel4);
        jLabel4.setBounds(740, 10, 100, 120);

        jLabel2.setText("Phone  (0251) 2324254   Email : KingdomHotel@heaven.com");
        pnlAwal.add(jLabel2);
        jLabel2.setBounds(320, 420, 330, 20);

        jLabel3.setText("Kingdom Hotel. Build by  a solid team, ABCD.");
        pnlAwal.add(jLabel3);
        jLabel3.setBounds(20, 330, 260, 14);

        jLabel5.setText("Jl. Dewata Raya 1994 ");
        pnlAwal.add(jLabel5);
        jLabel5.setBounds(320, 380, 300, 20);

        jLabel6.setText("Bogor - Indonesia 300194");
        pnlAwal.add(jLabel6);
        jLabel6.setBounds(320, 400, 160, 20);

        jLabel7.setText("Kingdom Hotel");
        pnlAwal.add(jLabel7);
        jLabel7.setBounds(320, 360, 100, 20);

        jLabel8.setText("This system information was design for ");
        pnlAwal.add(jLabel8);
        jLabel8.setBounds(20, 310, 260, 14);

        jLabel9.setText("Thank you");
        pnlAwal.add(jLabel9);
        jLabel9.setBounds(20, 430, 260, 20);

        jLabel10.setText("as their final project in PBO class. ");
        pnlAwal.add(jLabel10);
        jLabel10.setBounds(20, 370, 260, 20);

        jLabel11.setText("Alin, Binar, Cici, Dita and Helped by Octa");
        pnlAwal.add(jLabel11);
        jLabel11.setBounds(20, 350, 260, 20);

        jLabel12.setText("December 2013");
        pnlAwal.add(jLabel12);
        jLabel12.setBounds(20, 390, 260, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Gambar/hotel.jpg"))); // NOI18N
        pnlAwal.add(jLabel13);
        jLabel13.setBounds(20, 130, 210, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try{
        String password = new String(txtPass.getPassword());
        stm = Con.createStatement();
        RsUser=stm.executeQuery("select * from karyawan where userID='"+
        txtUser.getText()+"' and passID= '"+password+"'");
        int baris=0;
        while(RsUser.next()) {
        baris = RsUser.getRow();
        }
        if(baris==1)//mengecek ada berapa files dengan pass dan user itu, kalo satu benar kalo 0 salah
        {
        JOptionPane.showMessageDialog(null, "Welcome to Kingdom Hotel");
        new transaksi().setVisible(true);
        this.dispose();
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Invalid, please try again! "+txtUser.getText());
        }
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

private void pnlAwalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlAwalAncestorAdded
// TODO add your handling code here:
     //   int a=2147483647;
      //  pnlAwal.setMaximumSize(a);
        
}//GEN-LAST:event_pnlAwalAncestorAdded

    private void open_db()
    {
        try{
        KoneksiMysql kon = new KoneksiMysql ("localhost","root","","hotel");
        Con = kon.getConnection();
        }catch (Exception e) {
        System.out.println("Error : "+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       //login a = new login();
        
       // a.show();
      //  a.setExtendedState(MAXIMIZED_BOTH);
        
       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblGambar2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlAwal;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
